### ISSUE TITLE
webviewSetAppCookieKeyAndValue 代理方法不执行大佬哪个地方的原因

### ISSUE THREAD

**Issue by zhuyonghao134123** [GaoGuohao/GGWkCookie#1]

**Comment by GaoGuohao** [comment]
检查：
1.```< GGWkWebViewDelegate >```是否实现?
2.是否设置cookie代理 ?
```webView.cookieDelegate = self;```
3.是否开启自定义cookie开关（在loadRequest前开启）?
``` [webView startCustomCookie];```

如果以上步骤都实现，还是有问题，可以加我QQ：1158116271，我们私聊

需要注意的是，如果使用了 WebViewJavascriptBridge，WKNavigationDelegate代理的didCommitNavigation代理方法并不会被调用，如果需要打印cookie，需要在 didFinishNavigation 代理方法中打印。
```
// 使用 WebViewJavascriptBridge后 此代理方法不被调用
- (void)webView:(WKWebView *)webView didCommitNavigation:(WKNavigation *)navigation {}
```

**Comment by zhuyonghao134123** [comment]
牛皮大佬 给你点个赞👍
