### ISSUE TITLE
预设的JS脚本有一定局限性, 建议提供方法让用户可以设置自己的脚本

### ISSUE THREAD

**Issue by captain-black** [GaoGuohao/GGWkCookie#5]
我的顶级域名是.tech, 脚本里没支持个域名,所以设置cookie失败. 建议提供方法让用户可以设置自己的脚本

**Comment by GaoGuohao** [comment]
这几天修改一下，谢谢反馈！


| |


|
|
***@***.***
|


在2021年05月10日 ***@***.***> 写道：

我的顶级域名是.tech, 脚本里没支持个域名,所以设置cookie失败. 建议提供方法让用户可以设置自己的脚本
