### ISSUE TITLE
fatal: unable to access 'https://github.com/gaoguohao/GGWkCookie.git/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

### ISSUE THREAD

**Issue by boai** [GaoGuohao/GGWkCookie#7]
pod update  报错：
fatal: unable to access 'https://github.com/gaoguohao/GGWkCookie.git/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

**Comment by GaoGuohao** [comment]
> 

应该是git本地设置的问题，尝试一下：
`git config --global http.version HTTP/1.1`

**Comment by boai** [comment]
> 应该是git本地设置的问题，尝试一下：
> `git config --global http.version HTTP/1.1`

好的，谢谢大佬
